CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(40),
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_app_users_email UNIQUE (email),
    CONSTRAINT ck_app_users_role CHECK (role IN ('ADMIN', 'CLIENT'))
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    duration_minutes INTEGER NOT NULL,
    price NUMERIC(12, 2),
    active BOOLEAN NOT NULL,
    CONSTRAINT ck_services_duration_positive CHECK (duration_minutes > 0)
);

CREATE TABLE professionals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL,
    phone VARCHAR(40),
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_professionals_email UNIQUE (email)
);

CREATE TABLE business_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_business_hours_professional FOREIGN KEY (professional_id) REFERENCES professionals (id),
    CONSTRAINT ck_business_hours_day CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    CONSTRAINT ck_business_hours_range CHECK (start_time < end_time)
);

CREATE TABLE availability_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP NOT NULL,
    reason VARCHAR(300),
    type VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_availability_blocks_professional FOREIGN KEY (professional_id) REFERENCES professionals (id),
    CONSTRAINT ck_availability_blocks_type CHECK (type IN ('VACATION', 'SICK_LEAVE', 'HOLIDAY', 'MANUAL_BLOCK', 'OTHER')),
    CONSTRAINT ck_availability_blocks_range CHECK (start_date_time < end_date_time)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    professional_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,
    notes VARCHAR(500),
    cancel_reason VARCHAR(300),
    rejection_reason VARCHAR(300),
    created_by_role VARCHAR(20) NOT NULL,
    confirmed_at TIMESTAMP,
    canceled_at TIMESTAMP,
    completed_at TIMESTAMP,
    no_show_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_appointments_client FOREIGN KEY (client_id) REFERENCES app_users (id),
    CONSTRAINT fk_appointments_professional FOREIGN KEY (professional_id) REFERENCES professionals (id),
    CONSTRAINT fk_appointments_service FOREIGN KEY (service_id) REFERENCES services (id),
    CONSTRAINT ck_appointments_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELED_BY_CLIENT', 'CANCELED_BY_ADMIN', 'REJECTED', 'COMPLETED', 'NO_SHOW')),
    CONSTRAINT ck_appointments_created_by_role CHECK (created_by_role IN ('ADMIN', 'CLIENT')),
    CONSTRAINT ck_appointments_range CHECK (start_date_time < end_date_time)
);

CREATE INDEX idx_business_hours_professional_day ON business_hours (professional_id, day_of_week);
CREATE INDEX idx_availability_blocks_professional_range ON availability_blocks (professional_id, start_date_time, end_date_time);
CREATE INDEX idx_appointments_client ON appointments (client_id);
CREATE INDEX idx_appointments_professional_range ON appointments (professional_id, start_date_time, end_date_time);
CREATE INDEX idx_appointments_status ON appointments (status);
