CREATE TABLE service_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(140) NOT NULL,
    description VARCHAR(500),
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_service_categories_slug UNIQUE (slug)
);

INSERT INTO service_categories (id, name, slug, description, display_order, active) VALUES
    (1, 'Sin categoria', 'sin-categoria', 'Categoria temporal para servicios existentes o fixtures internos.', 0, TRUE),
    (2, 'Recuperacion capilar', 'recuperacion-capilar', 'Tratamientos orientados a fortalecer el cabello y acompanar casos de caida o debilitamiento.', 10, TRUE),
    (3, 'Estetica facial', 'estetica-facial', 'Procedimientos para mejorar la calidad de la piel y acompanar el cuidado facial.', 20, TRUE),
    (4, 'Estetica corporal', 'estetica-corporal', 'Tratamientos corporales orientados al cuidado de la piel, modelacion y bienestar.', 30, TRUE),
    (5, 'Pestanas y cejas', 'pestanas-cejas', 'Servicios para realzar la mirada con terminaciones prolijas y personalizadas.', 40, TRUE),
    (6, 'Podologia', 'podologia', 'Cuidado profesional de los pies para mejorar bienestar, higiene y confort diario.', 50, TRUE);

ALTER TABLE service_categories ALTER COLUMN id RESTART WITH 7;

ALTER TABLE services
    ADD COLUMN category_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE services
    ADD CONSTRAINT fk_services_category FOREIGN KEY (category_id) REFERENCES service_categories (id);

CREATE INDEX idx_services_category_id ON services (category_id);
