CREATE TABLE business (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(140) NOT NULL,
    timezone VARCHAR(60) NOT NULL DEFAULT 'America/Argentina/Buenos_Aires',
    whatsapp VARCHAR(40),
    primary_color VARCHAR(20),
    theme_preset VARCHAR(30),
    booking_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    plan_type VARCHAR(20) NOT NULL DEFAULT 'FREE',
    mp_access_token VARCHAR(255),
    show_branding BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_business_slug UNIQUE (slug),
    CONSTRAINT ck_business_plan_type CHECK (plan_type IN ('FREE', 'PRO'))
);

-- Insert default business (BIBE Estética)
INSERT INTO business (id, name, slug, timezone, whatsapp, primary_color, theme_preset, booking_enabled, plan_type, show_branding, active, created_at)
VALUES (1, 'BIBE Estetica', 'bibe', 'America/Argentina/Buenos_Aires', '+54 9 11 1234-5678', '#ff007f', 'aesthetic-pink', TRUE, 'PRO', FALSE, TRUE, CURRENT_TIMESTAMP);

-- Restart the business sequence so new ones start at 2
ALTER TABLE business ALTER COLUMN id RESTART WITH 2;

-- Drop old unique constraints
ALTER TABLE app_users DROP CONSTRAINT uk_app_users_email;
ALTER TABLE professionals DROP CONSTRAINT uk_professionals_email;
ALTER TABLE service_categories DROP CONSTRAINT uk_service_categories_slug;

-- Add business_id column to existing tables
ALTER TABLE app_users ADD COLUMN business_id BIGINT;
ALTER TABLE services ADD COLUMN business_id BIGINT;
ALTER TABLE service_categories ADD COLUMN business_id BIGINT;
ALTER TABLE professionals ADD COLUMN business_id BIGINT;
ALTER TABLE business_hours ADD COLUMN business_id BIGINT;
ALTER TABLE availability_blocks ADD COLUMN business_id BIGINT;
ALTER TABLE appointments ADD COLUMN business_id BIGINT;

-- Link existing records to the default business
UPDATE app_users SET business_id = 1;
UPDATE services SET business_id = 1;
UPDATE service_categories SET business_id = 1;
UPDATE professionals SET business_id = 1;
UPDATE business_hours SET business_id = 1;
UPDATE availability_blocks SET business_id = 1;
UPDATE appointments SET business_id = 1;

-- Alter columns to be NOT NULL
ALTER TABLE app_users ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE services ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE service_categories ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE professionals ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE business_hours ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE availability_blocks ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE appointments ALTER COLUMN business_id SET NOT NULL;

-- Add foreign key constraints
ALTER TABLE app_users ADD CONSTRAINT fk_app_users_business FOREIGN KEY (business_id) REFERENCES business (id);
ALTER TABLE services ADD CONSTRAINT fk_services_business FOREIGN KEY (business_id) REFERENCES business (id);
ALTER TABLE service_categories ADD CONSTRAINT fk_service_categories_business FOREIGN KEY (business_id) REFERENCES business (id);
ALTER TABLE professionals ADD CONSTRAINT fk_professionals_business FOREIGN KEY (business_id) REFERENCES business (id);
ALTER TABLE business_hours ADD CONSTRAINT fk_business_hours_business FOREIGN KEY (business_id) REFERENCES business (id);
ALTER TABLE availability_blocks ADD CONSTRAINT fk_availability_blocks_business FOREIGN KEY (business_id) REFERENCES business (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_business FOREIGN KEY (business_id) REFERENCES business (id);

-- Recreate unique constraints with business_id
ALTER TABLE app_users ADD CONSTRAINT uk_app_users_business_email UNIQUE (business_id, email);
ALTER TABLE professionals ADD CONSTRAINT uk_professionals_business_email UNIQUE (business_id, email);
ALTER TABLE service_categories ADD CONSTRAINT uk_service_categories_business_slug UNIQUE (business_id, slug);

-- Add public_uuid to appointments
ALTER TABLE appointments ADD COLUMN public_uuid UUID;
-- Generate random UUIDs for existing appointments
UPDATE appointments SET public_uuid = gen_random_uuid();
ALTER TABLE appointments ALTER COLUMN public_uuid SET NOT NULL;
ALTER TABLE appointments ADD CONSTRAINT uk_appointments_public_uuid UNIQUE (public_uuid);
