-- Insert Demo Barber business
INSERT INTO business (id, name, slug, timezone, whatsapp, primary_color, theme_preset, booking_enabled, plan_type, show_branding, active, created_at)
VALUES (2, 'Demo Barber', 'demo-barber', 'America/Argentina/Buenos_Aires', '+54 9 11 9999-0000', '#2563eb', 'modern-blue', TRUE, 'FREE', TRUE, TRUE, CURRENT_TIMESTAMP);

-- Restart the business sequence or let Hibernate know the next ID (since we manually inserted id=2, reset H2/Postgres counter if needed)
-- In Postgres/H2, if ID is GENERATED BY DEFAULT AS IDENTITY, it is safe to restart with 3
ALTER TABLE business ALTER COLUMN id RESTART WITH 3;

-- Insert admin user for Demo Barber (password: demo1234)
INSERT INTO app_users (full_name, email, password_hash, phone, role, active, created_at, business_id)
VALUES ('Admin Demo Barber', 'admin@demo-barber.com', '$2a$10$E2upv7arNzFdB2ZeuaDY5uSPS0DMZ5.4v5C/41HmqLur6s4yGv4U2', '+54 9 11 9999-0000', 'ADMIN', TRUE, CURRENT_TIMESTAMP, 2);

-- Insert service categories for Demo Barber
INSERT INTO service_categories (name, slug, display_order, active, business_id)
VALUES ('Cortes', 'cortes', 10, TRUE, 2);

INSERT INTO service_categories (name, slug, display_order, active, business_id)
VALUES ('Barba', 'barba', 20, TRUE, 2);

INSERT INTO service_categories (name, slug, display_order, active, business_id)
VALUES ('Tratamientos', 'tratamientos', 30, TRUE, 2);

-- Insert services for Demo Barber
INSERT INTO services (name, description, duration_minutes, price, active, business_id, category_id, online_bookable, requires_evaluation)
VALUES ('Corte clásico', 'Corte de pelo clásico con tijera y máquina.', 30, 5000.00, TRUE, 2, (SELECT id FROM service_categories WHERE business_id = 2 AND slug = 'cortes'), TRUE, FALSE);

INSERT INTO services (name, description, duration_minutes, price, active, business_id, category_id, online_bookable, requires_evaluation)
VALUES ('Fade', 'Corte moderno con degradado lateral a elección.', 45, 7000.00, TRUE, 2, (SELECT id FROM service_categories WHERE business_id = 2 AND slug = 'cortes'), TRUE, FALSE);

INSERT INTO services (name, description, duration_minutes, price, active, business_id, category_id, online_bookable, requires_evaluation)
VALUES ('Barba completa', 'Recorte, perfilado y afeitado con toalla caliente.', 20, 3500.00, TRUE, 2, (SELECT id FROM service_categories WHERE business_id = 2 AND slug = 'barba'), TRUE, FALSE);

INSERT INTO services (name, description, duration_minutes, price, active, business_id, category_id, online_bookable, requires_evaluation)
VALUES ('Corte + Barba', 'Servicio completo de corte clásico o fade y perfilado de barba.', 50, 8000.00, TRUE, 2, (SELECT id FROM service_categories WHERE business_id = 2 AND slug = 'cortes'), TRUE, FALSE);

-- Insert professionals for Demo Barber
INSERT INTO professionals (full_name, email, phone, active, service_assignment_mode, business_id)
VALUES ('Carlos Barbero', 'carlos@demo-barber.com', '+54 9 11 9999-0001', TRUE, 'ALL_SERVICES', 2);

INSERT INTO professionals (full_name, email, phone, active, service_assignment_mode, business_id)
VALUES ('Juan Navaja', 'juan@demo-barber.com', '+54 9 11 9999-0002', TRUE, 'ALL_SERVICES', 2);

-- Insert business hours for Carlos Barbero
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'carlos@demo-barber.com'), 'MONDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'carlos@demo-barber.com'), 'TUESDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'carlos@demo-barber.com'), 'WEDNESDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'carlos@demo-barber.com'), 'THURSDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'carlos@demo-barber.com'), 'FRIDAY', '09:00:00', '18:00:00', TRUE, 2);

-- Insert business hours for Juan Navaja
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'juan@demo-barber.com'), 'MONDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'juan@demo-barber.com'), 'TUESDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'juan@demo-barber.com'), 'WEDNESDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'juan@demo-barber.com'), 'THURSDAY', '09:00:00', '18:00:00', TRUE, 2);
INSERT INTO business_hours (professional_id, day_of_week, start_time, end_time, active, business_id)
VALUES ((SELECT id FROM professionals WHERE business_id = 2 AND email = 'juan@demo-barber.com'), 'FRIDAY', '09:00:00', '18:00:00', TRUE, 2);
